contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "MPHY0021: Research Software Engineering With Python"
includeleftnav: True
short: MPHY0021

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /rsd-engineeringcourse

remote_theme: dpshelio/indigo-jekyll

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: Our services
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: Research IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: Training

kramdown:
  hard_wrap: false

plugins:
  - jekyll-remote-theme

include: # NOTE: This is not a path, but the directories name, wherever they are
  - _static
  - _modules

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - "*/*.nbconvert.ipynb"
  - "*/*.v2.ipynb"
  - "combined_files"
  - "combined.ipynb"
